require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.completion"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.lsp"
require "user.comments"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"

