require("catppuccin").setup {
  -- transparent_background = true,
  flavour = "mocha",
  styles = {
    comments = { "italic" }, -- Change the style of comments
    conditionals = { "italic" },
    loops = {},
    functions = {},
    keywords = {},
    strings = {},
    variables = {},
    numbers = {},
    booleans = {},
    properties = {},
    types = {},
    operators = {},
  },
  color_overrides = {
    latte = {
      rosewater = "#cc7983",
      flamingo = "#bb5d60",
      pink = "#d54597",
      mauve = "#a65fd5",
      red = "#b7242f",
      maroon = "#db3e68",
      peach = "#e46f2a",
      yellow = "#bc8705",
      green = "#1a8e32",
      teal = "#00a390",
      sky = "#089ec0",
      sapphire = "#0ea0a0",
      blue = "#017bca",
      lavender = "#8584f7",
      text = "#444444",
      subtext1 = "#555555",
      subtext0 = "#666666",
      overlay2 = "#777777",
      overlay1 = "#888888",
      overlay0 = "#999999",
      surface2 = "#aaaaaa",
      surface1 = "#bbbbbb",
      surface0 = "#cccccc",
      base = "#fffff9",
      mantle = "#eeeeee",
      crust = "#dddddd",
    },
  },
  term_colors = true,
  integrations = {
    cmp = true,
    flash = false,
    gitsigns = true,
    mini = {
      enabled = false,
    },
    mason = true,
    markdown = true,
    neogit = true,
    neotest = true,
    nvimtree = false,
    ufo = true,
    telescope = { enabled = true, style = "nvchad" },
    treesitter = true,
    lsp_saga = false,
  },
  ---@diagnostic disable-next-line: unused-local
  custom_highlights = function(_colors)
    return {
      FloatBorder = { link = "NormalFloat" },
    }
  end,
}
