require("oldworld").setup {
  terminal_colors = true, -- enable terminal colors
  styles = { -- You can pass the style using the format: style = true
    comments = { italic = true },
    keywords = {}, -- style for keywords
    identifiers = {}, -- style for identifiers
    functions = {}, -- style for functions
    variables = {}, -- style for variables
    booleans = { italic = true }, -- style for booleans
  },
  integrations = { -- You can disable/enable integrations
    alpha = false,
    cmp = true,
    flash = true,
    gitsigns = true,
    hop = false,
    indent_blankline = false,
    lazy = true,
    lsp = true,
    markdown = true,
    mason = true,
    navic = false,
    neo_tree = false,
    neorg = false,
    noice = false,
    notify = false,
    rainbow_delimiters = false,
    telescope = true,
    treesitter = true,
  },
  highlight_overrides = {
    Visual = { link = "QuickFixLine" },
    NormalNC = { link = "Normal" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAddHighlight = { link = "DiffAdd" },
    NeogitDiffDeleteHighlight = { link = "DiffDelete" },
    TelescopePromptNormal = { link = "Pmenu" },
    TelescopePromptBorder = { link = "Pmenu" },
    TelescopePromptTitle = { link = "Pmenu" },
    TelescopePreviewNormal = { link = "Pmenu" },
    TelescopePreviewBorder = { link = "Pmenu" },
    TelescopePreviewTitle = { link = "Pmenu" },
    TelescopePreviewLine = { link = "CursorColumn" },
    TelescopePreviewSticky = { link = "WildMenu" },
    TelescopeResultsNormal = { link = "Pmenu" },
    TelescopeResultsBorder = { link = "Pmenu" },
    TelescopeResultsTitle = { link = "Pmenu" },
    SpellBad = { link = "Underlined" },
    CursorLine = { link = "CursorColumn" },
    ["@tag.attribute"] = { link = "Normal" },
    ["@markup.heading.1"] = { link = "Normal" },
    ["@markup.heading.2"] = { link = "Normal" },
    ["@markup.heading.3"] = { link = "Normal" },
    ["@markup.heading.4"] = { link = "Normal" },
    ["@markup.heading.5"] = { link = "Normal" },
    ["@markup.heading.6"] = { link = "Normal" },
    ["@tag.delimiter"] = { link = "Number" },
    ["@tag"] = { link = "Number" },
  },
}
